package com.devinolabs.uap.athlete.domain;

public enum GoalType {
	LOSE_WEIGHT,
	GAIN_WEIGHT,
	REDUCE_BODY_FAT,
	GAIN_MUSCLE,
	IMPROVE_STRENGTH,
	IMPROVE_POWER,
	INCREASE_VERTICAL_JUMP,
	IMPROVE_SPEED,
	IMPROVE_AGILITY,
	IMPROVE_ENDURANCE,
	IMPROVE_MOBILITY,
	IMPROVE_FLEXIBILITY,
	IMPROVE_BALANCE,
	IMPROVE_SPORT_PERFORMANCE,
	RETURN_FROM_INJURY,
	RUN_DISTANCE,
	RUN_EVENT,
	CYCLING_EVENT,
	SWIMMING_EVENT,
	TRIATHLON_EVENT,
	GENERAL_FITNESS,
	MAINTENANCE,
	OTHER
}
