packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@ampproject/toolbox-optimizer': true
  '@parcel/watcher': true
  es5-ext: true
  esbuild: true
  fsevents: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.14 || 57.0.28'
  - '@expo/fingerprint@0.20.7'
  - '@expo/inline-modules@0.1.5'
  - '@expo/local-build-cache-provider@57.0.6'
  - '@expo/metro-config@57.0.8 || 57.0.13'
  - '@expo/metro-runtime@57.0.9'
  - '@expo/prebuild-config@57.0.11 || 57.0.17'
  - '@expo/ui@57.0.10 || 57.0.22'
  - expo-asset@57.0.10 || 57.0.19
  - expo-constants@57.0.10 || 57.0.21
  - expo-dev-client@57.0.11
  - expo-dev-launcher@57.0.11
  - expo-dev-menu@57.0.11
  - expo-router@57.0.12 || 57.0.25
  - expo-server@57.0.2
  - expo-splash-screen@57.0.6
  - expo@57.0.12 || 57.0.27
  - '@expo/config-plugins@57.0.10'
  - '@expo/config@57.0.10'
  - '@expo/image-utils@0.11.6'
  - '@expo/metro-file-map@57.0.4'
  - '@expo/require-utils@57.0.6'
  - '@expo/router-server@57.0.12'
  - babel-preset-expo@57.0.14
  - expo-modules-autolinking@57.0.14
  - expo-modules-core@57.0.21
  - expo-linking@57.0.12
patchedDependencies:
  '@react-native-cookies/cookies@6.2.1': patches/@react-native-cookies__cookies@6.2.1.patch
  react-native-health@1.19.0: patches/react-native-health@1.19.0.patch
