package com.devinolabs.uap.training.domain;

public enum DailyAthleteStateGenerationReason {
	MANUAL,
	RECOVERY_CHECK_IN_CREATED,
	RECOVERY_CHECK_IN_UPDATED,
	TRAINING_COMPLETED,
	SESSION_EFFORT_CREATED,
	SESSION_EFFORT_UPDATED,
	TRAINING_LOAD_RECOMPUTED,
	TRAINING_LOAD_REBUILT,
	SCHEDULE_CHANGED,
	REGENERATED
}
