package com.devinolabs.uap.training.domain;

public enum ExerciseSubstitutionRelationshipType {

	EQUIVALENT_VARIATION,
	EQUIPMENT_ALTERNATIVE,
	REGRESSION,
	PROGRESSION,
	LOWER_IMPACT_ALTERNATIVE,
	UNILATERAL_ALTERNATIVE,
	BILATERAL_ALTERNATIVE,
	TEMPORARY_MODIFICATION,
	SPORT_SPECIFIC_VARIATION,
	OTHER

}
