package com.devinolabs.uap.training.domain;

/**
 * Stable explanatory codes for feasibility analysis results. These are not HTTP errors.
 */
public enum FeasibilityReasonCode {

	ALL_REQUIRED_EQUIPMENT_AVAILABLE,
	NO_REQUIRED_EQUIPMENT,
	MISSING_REQUIRED_EQUIPMENT,
	COMPATIBLE_SUBSTITUTION_FOUND,
	NO_ACTIVE_SUBSTITUTION_RELATIONSHIP,
	RELATIONSHIP_TARGET_REQUIRES_MISSING_EQUIPMENT,
	EXERCISE_DEFINITION_ARCHIVED,
	NO_ENVIRONMENT_CONTEXT,
	EXERCISE_DEFINITION_NOT_ACCESSIBLE,
	HISTORICAL_SNAPSHOT_ANALYSIS

}
