package com.devinolabs.uap.training.domain;

public enum ReadinessReasonCode {
	BASELINE_ALIGNED,
	ABOVE_PERSONAL_BASELINE,
	BELOW_PERSONAL_BASELINE,
	FAR_ABOVE_PERSONAL_BASELINE,
	FAR_BELOW_PERSONAL_BASELINE,
	TARGET_VALUE_MISSING,
	BASELINE_INSUFFICIENT,
	ZERO_BASELINE_VARIANCE_FALLBACK,
	DIMENSION_EXCLUDED,
	CONTEXT_ONLY,
	READINESS_DATA_INSUFFICIENT,
	READINESS_CALCULATED
}
