package com.devinolabs.uap.training.domain;

/**
 * Deterministic recommendation explanation codes.
 */
public enum TrainingRecommendationReasonCode {
	READINESS_HIGH,
	READINESS_MODERATE,
	READINESS_LOW,
	READINESS_INSUFFICIENT,
	NO_SCHEDULED_TRAINING,
	TRAINING_ALREADY_COMPLETED,
	FATIGUE_LIMITING,
	SORENESS_LIMITING,
	STRESS_LIMITING,
	MOOD_LIMITING,
	MOTIVATION_LIMITING,
	SLEEP_QUALITY_LIMITING,
	SLEEP_DURATION_LIMITING,
	MULTIPLE_LIMITING_DIMENSIONS,
	NO_ADJUSTMENT_REQUIRED
}
